### ISSUE TITLE
OCR Front Window

### ISSUE THREAD

**Issue by Nils31011992** [chigkim/VOCR#4] opened 2017-08-27 16:29 UTC
If I Scan the Screen, the following Error appears:
/var/folders/7c/nl8j8s0n5ps7v52bdn7wr0hw0000gn/T/Keyboard-Maestro-Script-4BC595B6-AEB3-454B-976B-6C1EA6EC078C:2360:2392: execution error: Error on line 72: ReferenceError: Can't find variable: str (-2700)

**Comment by chigkim** [comment] 2017-08-27 16:35
Please do not create a new issue. Comment on the issue you've already created before instead.
It looks like you do not have the latest macros. Redownload, import, try again, and send me the report.
Duplicate of #1

**Closed by chigkim** 2017-08-27 16:35 UTC
