### ISSUE TITLE
Error with OCR Front Window Macro

### ISSUE THREAD

**Issue by Nils31011992** [chigkim/VOCR#5] opened 2017-08-27 17:00 UTC
After Scanning, the following Error Appears:
/var/folders/7c/nl8j8s0n5ps7v52bdn7wr0hw0000gn/T/Keyboard-Maestro-Script-5281AD59-443A-4FDF-9EC4-448192CAD144:2360:2392: execution error: Error on line 72: ReferenceError: Can't find variable: str (-2700)
I downloaded the newest commit and replaced the old Macros.

**Comment by chigkim** [comment] 2017-08-27 17:44
I updated with some changes. Try again please.  
Again, do not create a new issue. Comment on the #1.  
Duplicate of #1

**Closed by chigkim** 2017-08-27 17:44 UTC
