### ISSUE TITLE
Error with Macro Front Window xyz

### ISSUE THREAD

**Issue by Nils31011992** [chigkim/VOCR#3] opened 2017-08-27 10:02 UTC
Now the following error appears, after I made a Screenshot.
/var/folders/7c/nl8j8s0n5ps7v52bdn7wr0hw0000gn/T/Keyboard-Maestro-Script-D1F8938A-F77B-4A17-B1D0-0B9A6F565984:2020:2050: execution error: Error on line 60: Error: Die Datei wurde nicht gefunden. (-43)

**Comment by chigkim** [comment] 2017-08-27 11:00
Did you redownload the latest macros and import them using the import application? Can you copy paste the entire log? There should be more.

**Comment by Nils31011992** [comment] 2017-08-27 11:09
Yes, I did
How can I get the log?

Von meinem iPhone gesendet

**Comment by chigkim** [comment] 2017-08-27 11:37
Ok this might have to do with German language. Try the latest and see if it works.

**Comment by chigkim** [comment] 2017-08-27 15:48
Duplicate of #1

**Closed** 2017-08-27 16:38 UTC
